version: '3.8'

services:
  backend:
    build: ./backend
    container_name: crset_fullstack_starter-backend-1
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/code/app
    environment:
      - PYTHONPATH=/code
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
