version: '3.8'

# Configurações específicas para desenvolvimento
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    ports:
      - "3000:3000"
      - "9229:9229" # Debug port

  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=financeflow_dev
      - POSTGRES_USER=financeflow
      - POSTGRES_PASSWORD=financeflow123

  # Adminer para gestão da base de dados em desenvolvimento
  adminer:
    image: adminer
    container_name: financeflow-adminer
    ports:
      - "8080:8080"
    networks:
      - financeflow-network
    depends_on:
      - db

